# Generated by Django 6.0.4 on 2026-04-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdisease',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Leaf_Photos/'),
        ),
    ]
