# Generated by Django 5.2.7 on 2026-04-27 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Former', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_model',
            name='email',
        ),
    ]
