# Generated by Django 6.0.4 on 2026-04-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pestclass',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Pest_Photos/'),
        ),
    ]
